# Builds and deploys Frontend project to Firebase Hosting frontend target's Live channel

name: Deploy to Firebase Hosting on merge of Frontend changes
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ARA_WEBSITE_9ADF7 }}'
          channelId: live
          projectId: ara-website-9adf7
          entryPoint: "./frontend" 
          target: frontend
